nodeLinker: node-modules

# Para que Yarn instale las dependencias opcionales de sharp (libvips) en darwin-arm64
# https://sharp.pixelplumbing.com/install#cross-platform | yarn v3+
supportedArchitectures:
  os: [darwin]
  cpu: [arm64]
