// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Episode → Introduction*
 */
export interface EpisodeDocumentDataIntroductionItem {
  /**
   * Episode field in *Episode → Introduction*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].episode
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  episode: prismic.NumberField;

  /**
   * Date field in *Episode → Introduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Title field in *Episode → Introduction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Guest field in *Episode → Introduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].guest
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  guest: prismic.KeyTextField;

  /**
   * Business field in *Episode → Introduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].business
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  business: prismic.KeyTextField;

  /**
   * Category field in *Episode → Introduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * Description field in *Episode → Introduction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Insights field in *Episode → Introduction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].insights
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  insights: prismic.RichTextField;

  /**
   * Spotify field in *Episode → Introduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].spotify
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spotify: prismic.KeyTextField;

  /**
   * Google field in *Episode → Introduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].google
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google: prismic.KeyTextField;

  /**
   * Apple field in *Episode → Introduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].apple
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  apple: prismic.KeyTextField;

  /**
   * Youtube field in *Episode → Introduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].youtube
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube: prismic.KeyTextField;
}

/**
 * Item in *Episode → Images*
 */
export interface EpisodeDocumentDataImagesItem {
  /**
   * Podcast field in *Episode → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[].episode
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  episode: prismic.ImageField<never>;

  /**
   * Solas field in *Episode → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[].solas
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  solas: prismic.ImageField<never>;

  /**
   * Youtube field in *Episode → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[].youtube
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  youtube: prismic.ImageField<never>;

  /**
   * Gif  field in *Episode → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[].gif
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gif: prismic.ImageField<never>;
}

/**
 * Content for Episode documents
 */
interface EpisodeDocumentData {
  /**
   * Introduction field in *Episode*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  introduction: prismic.GroupField<
    Simplify<EpisodeDocumentDataIntroductionItem>
  >;

  /**
   * Body field in *Episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Images field in *Episode*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<EpisodeDocumentDataImagesItem>>;
}

/**
 * Episode document from Prismic
 *
 * - **API ID**: `episode`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EpisodeDocumentData>,
    "episode",
    Lang
  >;

export type AllDocumentTypes = EpisodeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type { EpisodeDocument, EpisodeDocumentData, AllDocumentTypes };
  }
}
