// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Episode → Introducción*
 */
export interface EpisodeDocumentDataIntroductionItem {
  /**
   * Título del episodio field in *Episode → Introducción*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sin número, ni invitado, ni empresa
   * - **API ID Path**: episode.introduction[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Número del episodio field in *Episode → Introducción*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].episode
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  episode: prismic.NumberField;

  /**
   * Fecha de publicación planeada field in *Episode → Introducción*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Invitado field in *Episode → Introducción*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].guest
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  guest: prismic.KeyTextField;

  /**
   * Empresa field in *Episode → Introducción*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].business
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  business: prismic.KeyTextField;

  /**
   * Categoría field in *Episode → Introducción*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[].category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | "Founder"
    | "Producto"
    | "Operador"
    | "People"
    | "Innovacion"
    | "Desarrollo"
    | "Inversor"
    | "Growth"
  >;

  /**
   * Descripción field in *Episode → Introducción*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Excluye: "Lo más importante que pueden aprender operadores... es lo siguiente:"
   * - **API ID Path**: episode.introduction[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Insights field in *Episode → Introducción*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Convertir el texto en lista, la primera oración de cada punto en negrita
   * - **API ID Path**: episode.introduction[].insights
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  insights: prismic.RichTextField;

  /**
   * URL de Spotify field in *Episode → Introducción*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://www...
   * - **API ID Path**: episode.introduction[].spotify
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spotify: prismic.KeyTextField;

  /**
   * URL de Google field in *Episode → Introducción*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://www...
   * - **API ID Path**: episode.introduction[].google
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google: prismic.KeyTextField;

  /**
   * URL de Apple field in *Episode → Introducción*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://www...
   * - **API ID Path**: episode.introduction[].apple
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  apple: prismic.KeyTextField;

  /**
   * URL de Youtube field in *Episode → Introducción*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://www...
   * - **API ID Path**: episode.introduction[].youtube
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube: prismic.KeyTextField;
}

/**
 * Item in *Episode → Imagenes*
 */
export interface EpisodeDocumentDataImagesItem {
  /**
   * Portada del podcast (400x400) field in *Episode → Imagenes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[].episode
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  episode: prismic.ImageField<never>;

  /**
   * Ilustración (508x285) field in *Episode → Imagenes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[].solas
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  solas: prismic.ImageField<never>;

  /**
   * Portada de Youtube (1600x900) field in *Episode → Imagenes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[].youtube
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  youtube: prismic.ImageField<never>;

  /**
   * Gif para compartir, OpenG (800x800) field in *Episode → Imagenes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[].gif
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gif: prismic.ImageField<never>;
}

/**
 * Content for Episode documents
 */
interface EpisodeDocumentData {
  /**
   * Introducción field in *Episode*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.introduction[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  introduction: prismic.GroupField<
    Simplify<EpisodeDocumentDataIntroductionItem>
  >;

  /**
   * Body field in *Episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Imagenes field in *Episode*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<EpisodeDocumentDataImagesItem>>;
}

/**
 * Episode document from Prismic
 *
 * - **API ID**: `episode`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EpisodeDocumentData>,
    "episode",
    Lang
  >;

export type AllDocumentTypes = EpisodeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EpisodeDocument,
      EpisodeDocumentData,
      EpisodeDocumentDataIntroductionItem,
      EpisodeDocumentDataImagesItem,
      AllDocumentTypes,
    };
  }
}
